/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSimulatorRouteImport } from './routes/_authenticated/simulator'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPredictionRouteImport } from './routes/_authenticated/prediction'
import { Route as AuthenticatedMethodologyRouteImport } from './routes/_authenticated/methodology'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated/map'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCompoundRouteImport } from './routes/_authenticated/compound'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicOtpVerifyRouteImport } from './routes/api/public/otp.verify'
import { Route as ApiPublicOtpSendRouteImport } from './routes/api/public/otp.send'
import { Route as ApiPublicIngestLatestRouteImport } from './routes/api/public/ingest.latest'
import { Route as ApiPublicIngestClimateRouteImport } from './routes/api/public/ingest.climate'
import { Route as ApiPublicHooksIngestImdRouteImport } from './routes/api/public/hooks/ingest-imd'
import { Route as ApiPublicHooksIngestForecastRouteImport } from './routes/api/public/hooks/ingest-forecast'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSimulatorRoute = AuthenticatedSimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPredictionRoute = AuthenticatedPredictionRouteImport.update({
  id: '/prediction',
  path: '/prediction',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMethodologyRoute =
  AuthenticatedMethodologyRouteImport.update({
    id: '/methodology',
    path: '/methodology',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompoundRoute = AuthenticatedCompoundRouteImport.update({
  id: '/compound',
  path: '/compound',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicOtpVerifyRoute = ApiPublicOtpVerifyRouteImport.update({
  id: '/api/public/otp/verify',
  path: '/api/public/otp/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOtpSendRoute = ApiPublicOtpSendRouteImport.update({
  id: '/api/public/otp/send',
  path: '/api/public/otp/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestLatestRoute = ApiPublicIngestLatestRouteImport.update({
  id: '/api/public/ingest/latest',
  path: '/api/public/ingest/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestClimateRoute = ApiPublicIngestClimateRouteImport.update({
  id: '/api/public/ingest/climate',
  path: '/api/public/ingest/climate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksIngestImdRoute = ApiPublicHooksIngestImdRouteImport.update({
  id: '/api/public/hooks/ingest-imd',
  path: '/api/public/hooks/ingest-imd',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksIngestForecastRoute =
  ApiPublicHooksIngestForecastRouteImport.update({
    id: '/api/public/hooks/ingest-forecast',
    path: '/api/public/hooks/ingest-forecast',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/compound': typeof AuthenticatedCompoundRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/map': typeof AuthenticatedMapRoute
  '/methodology': typeof AuthenticatedMethodologyRoute
  '/prediction': typeof AuthenticatedPredictionRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/simulator': typeof AuthenticatedSimulatorRoute
  '/api/public/hooks/ingest-forecast': typeof ApiPublicHooksIngestForecastRoute
  '/api/public/hooks/ingest-imd': typeof ApiPublicHooksIngestImdRoute
  '/api/public/ingest/climate': typeof ApiPublicIngestClimateRoute
  '/api/public/ingest/latest': typeof ApiPublicIngestLatestRoute
  '/api/public/otp/send': typeof ApiPublicOtpSendRoute
  '/api/public/otp/verify': typeof ApiPublicOtpVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/compound': typeof AuthenticatedCompoundRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/map': typeof AuthenticatedMapRoute
  '/methodology': typeof AuthenticatedMethodologyRoute
  '/prediction': typeof AuthenticatedPredictionRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/simulator': typeof AuthenticatedSimulatorRoute
  '/api/public/hooks/ingest-forecast': typeof ApiPublicHooksIngestForecastRoute
  '/api/public/hooks/ingest-imd': typeof ApiPublicHooksIngestImdRoute
  '/api/public/ingest/climate': typeof ApiPublicIngestClimateRoute
  '/api/public/ingest/latest': typeof ApiPublicIngestLatestRoute
  '/api/public/otp/send': typeof ApiPublicOtpSendRoute
  '/api/public/otp/verify': typeof ApiPublicOtpVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/compound': typeof AuthenticatedCompoundRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/map': typeof AuthenticatedMapRoute
  '/_authenticated/methodology': typeof AuthenticatedMethodologyRoute
  '/_authenticated/prediction': typeof AuthenticatedPredictionRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/simulator': typeof AuthenticatedSimulatorRoute
  '/api/public/hooks/ingest-forecast': typeof ApiPublicHooksIngestForecastRoute
  '/api/public/hooks/ingest-imd': typeof ApiPublicHooksIngestImdRoute
  '/api/public/ingest/climate': typeof ApiPublicIngestClimateRoute
  '/api/public/ingest/latest': typeof ApiPublicIngestLatestRoute
  '/api/public/otp/send': typeof ApiPublicOtpSendRoute
  '/api/public/otp/verify': typeof ApiPublicOtpVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin'
    | '/alerts'
    | '/compound'
    | '/dashboard'
    | '/map'
    | '/methodology'
    | '/prediction'
    | '/reports'
    | '/settings'
    | '/simulator'
    | '/api/public/hooks/ingest-forecast'
    | '/api/public/hooks/ingest-imd'
    | '/api/public/ingest/climate'
    | '/api/public/ingest/latest'
    | '/api/public/otp/send'
    | '/api/public/otp/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin'
    | '/alerts'
    | '/compound'
    | '/dashboard'
    | '/map'
    | '/methodology'
    | '/prediction'
    | '/reports'
    | '/settings'
    | '/simulator'
    | '/api/public/hooks/ingest-forecast'
    | '/api/public/hooks/ingest-imd'
    | '/api/public/ingest/climate'
    | '/api/public/ingest/latest'
    | '/api/public/otp/send'
    | '/api/public/otp/verify'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/alerts'
    | '/_authenticated/compound'
    | '/_authenticated/dashboard'
    | '/_authenticated/map'
    | '/_authenticated/methodology'
    | '/_authenticated/prediction'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/simulator'
    | '/api/public/hooks/ingest-forecast'
    | '/api/public/hooks/ingest-imd'
    | '/api/public/ingest/climate'
    | '/api/public/ingest/latest'
    | '/api/public/otp/send'
    | '/api/public/otp/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicHooksIngestForecastRoute: typeof ApiPublicHooksIngestForecastRoute
  ApiPublicHooksIngestImdRoute: typeof ApiPublicHooksIngestImdRoute
  ApiPublicIngestClimateRoute: typeof ApiPublicIngestClimateRoute
  ApiPublicIngestLatestRoute: typeof ApiPublicIngestLatestRoute
  ApiPublicOtpSendRoute: typeof ApiPublicOtpSendRoute
  ApiPublicOtpVerifyRoute: typeof ApiPublicOtpVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/simulator': {
      id: '/_authenticated/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof AuthenticatedSimulatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prediction': {
      id: '/_authenticated/prediction'
      path: '/prediction'
      fullPath: '/prediction'
      preLoaderRoute: typeof AuthenticatedPredictionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/methodology': {
      id: '/_authenticated/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof AuthenticatedMethodologyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compound': {
      id: '/_authenticated/compound'
      path: '/compound'
      fullPath: '/compound'
      preLoaderRoute: typeof AuthenticatedCompoundRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/otp/verify': {
      id: '/api/public/otp/verify'
      path: '/api/public/otp/verify'
      fullPath: '/api/public/otp/verify'
      preLoaderRoute: typeof ApiPublicOtpVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/otp/send': {
      id: '/api/public/otp/send'
      path: '/api/public/otp/send'
      fullPath: '/api/public/otp/send'
      preLoaderRoute: typeof ApiPublicOtpSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest/latest': {
      id: '/api/public/ingest/latest'
      path: '/api/public/ingest/latest'
      fullPath: '/api/public/ingest/latest'
      preLoaderRoute: typeof ApiPublicIngestLatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest/climate': {
      id: '/api/public/ingest/climate'
      path: '/api/public/ingest/climate'
      fullPath: '/api/public/ingest/climate'
      preLoaderRoute: typeof ApiPublicIngestClimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ingest-imd': {
      id: '/api/public/hooks/ingest-imd'
      path: '/api/public/hooks/ingest-imd'
      fullPath: '/api/public/hooks/ingest-imd'
      preLoaderRoute: typeof ApiPublicHooksIngestImdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ingest-forecast': {
      id: '/api/public/hooks/ingest-forecast'
      path: '/api/public/hooks/ingest-forecast'
      fullPath: '/api/public/hooks/ingest-forecast'
      preLoaderRoute: typeof ApiPublicHooksIngestForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedCompoundRoute: typeof AuthenticatedCompoundRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMapRoute: typeof AuthenticatedMapRoute
  AuthenticatedMethodologyRoute: typeof AuthenticatedMethodologyRoute
  AuthenticatedPredictionRoute: typeof AuthenticatedPredictionRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSimulatorRoute: typeof AuthenticatedSimulatorRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedCompoundRoute: AuthenticatedCompoundRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMapRoute: AuthenticatedMapRoute,
  AuthenticatedMethodologyRoute: AuthenticatedMethodologyRoute,
  AuthenticatedPredictionRoute: AuthenticatedPredictionRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSimulatorRoute: AuthenticatedSimulatorRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicHooksIngestForecastRoute: ApiPublicHooksIngestForecastRoute,
  ApiPublicHooksIngestImdRoute: ApiPublicHooksIngestImdRoute,
  ApiPublicIngestClimateRoute: ApiPublicIngestClimateRoute,
  ApiPublicIngestLatestRoute: ApiPublicIngestLatestRoute,
  ApiPublicOtpSendRoute: ApiPublicOtpSendRoute,
  ApiPublicOtpVerifyRoute: ApiPublicOtpVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
