/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidationRouteImport } from './routes/validation'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PredictionRouteImport } from './routes/prediction'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as MapRouteImport } from './routes/map'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as DataSourcesRouteImport } from './routes/data-sources'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompoundRouteImport } from './routes/compound'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AttributionsRouteImport } from './routes/attributions'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidesKosiBasinHydrologyRouteImport } from './routes/guides.kosi-basin-hydrology'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicOtpVerifyRouteImport } from './routes/api/public/otp.verify'
import { Route as ApiPublicOtpSendRouteImport } from './routes/api/public/otp.send'
import { Route as ApiPublicIngestClimateRouteImport } from './routes/api/public/ingest.climate'

const ValidationRoute = ValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionRoute = PredictionRouteImport.update({
  id: '/prediction',
  path: '/prediction',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const DataSourcesRoute = DataSourcesRouteImport.update({
  id: '/data-sources',
  path: '/data-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompoundRoute = CompoundRouteImport.update({
  id: '/compound',
  path: '/compound',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AttributionsRoute = AttributionsRouteImport.update({
  id: '/attributions',
  path: '/attributions',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesKosiBasinHydrologyRoute =
  GuidesKosiBasinHydrologyRouteImport.update({
    id: '/guides/kosi-basin-hydrology',
    path: '/guides/kosi-basin-hydrology',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicOtpVerifyRoute = ApiPublicOtpVerifyRouteImport.update({
  id: '/api/public/otp/verify',
  path: '/api/public/otp/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOtpSendRoute = ApiPublicOtpSendRouteImport.update({
  id: '/api/public/otp/send',
  path: '/api/public/otp/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestClimateRoute = ApiPublicIngestClimateRouteImport.update({
  id: '/api/public/ingest/climate',
  path: '/api/public/ingest/climate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/attributions': typeof AttributionsRoute
  '/auth': typeof AuthRoute
  '/compound': typeof CompoundRoute
  '/dashboard': typeof DashboardRoute
  '/data-sources': typeof DataSourcesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/map': typeof MapRoute
  '/methodology': typeof MethodologyRoute
  '/prediction': typeof PredictionRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/validation': typeof ValidationRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/guides/kosi-basin-hydrology': typeof GuidesKosiBasinHydrologyRoute
  '/api/public/ingest/climate': typeof ApiPublicIngestClimateRoute
  '/api/public/otp/send': typeof ApiPublicOtpSendRoute
  '/api/public/otp/verify': typeof ApiPublicOtpVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/attributions': typeof AttributionsRoute
  '/auth': typeof AuthRoute
  '/compound': typeof CompoundRoute
  '/dashboard': typeof DashboardRoute
  '/data-sources': typeof DataSourcesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/map': typeof MapRoute
  '/methodology': typeof MethodologyRoute
  '/prediction': typeof PredictionRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/validation': typeof ValidationRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/guides/kosi-basin-hydrology': typeof GuidesKosiBasinHydrologyRoute
  '/api/public/ingest/climate': typeof ApiPublicIngestClimateRoute
  '/api/public/otp/send': typeof ApiPublicOtpSendRoute
  '/api/public/otp/verify': typeof ApiPublicOtpVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/alerts': typeof AlertsRoute
  '/attributions': typeof AttributionsRoute
  '/auth': typeof AuthRoute
  '/compound': typeof CompoundRoute
  '/dashboard': typeof DashboardRoute
  '/data-sources': typeof DataSourcesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/map': typeof MapRoute
  '/methodology': typeof MethodologyRoute
  '/prediction': typeof PredictionRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/validation': typeof ValidationRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/guides/kosi-basin-hydrology': typeof GuidesKosiBasinHydrologyRoute
  '/api/public/ingest/climate': typeof ApiPublicIngestClimateRoute
  '/api/public/otp/send': typeof ApiPublicOtpSendRoute
  '/api/public/otp/verify': typeof ApiPublicOtpVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/attributions'
    | '/auth'
    | '/compound'
    | '/dashboard'
    | '/data-sources'
    | '/disclaimer'
    | '/map'
    | '/methodology'
    | '/prediction'
    | '/privacy'
    | '/settings'
    | '/simulator'
    | '/sitemap.xml'
    | '/terms'
    | '/validation'
    | '/admin'
    | '/reports'
    | '/guides/kosi-basin-hydrology'
    | '/api/public/ingest/climate'
    | '/api/public/otp/send'
    | '/api/public/otp/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/attributions'
    | '/auth'
    | '/compound'
    | '/dashboard'
    | '/data-sources'
    | '/disclaimer'
    | '/map'
    | '/methodology'
    | '/prediction'
    | '/privacy'
    | '/settings'
    | '/simulator'
    | '/sitemap.xml'
    | '/terms'
    | '/validation'
    | '/admin'
    | '/reports'
    | '/guides/kosi-basin-hydrology'
    | '/api/public/ingest/climate'
    | '/api/public/otp/send'
    | '/api/public/otp/verify'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/alerts'
    | '/attributions'
    | '/auth'
    | '/compound'
    | '/dashboard'
    | '/data-sources'
    | '/disclaimer'
    | '/map'
    | '/methodology'
    | '/prediction'
    | '/privacy'
    | '/settings'
    | '/simulator'
    | '/sitemap.xml'
    | '/terms'
    | '/validation'
    | '/_authenticated/admin'
    | '/_authenticated/reports'
    | '/guides/kosi-basin-hydrology'
    | '/api/public/ingest/climate'
    | '/api/public/otp/send'
    | '/api/public/otp/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AlertsRoute: typeof AlertsRoute
  AttributionsRoute: typeof AttributionsRoute
  AuthRoute: typeof AuthRoute
  CompoundRoute: typeof CompoundRoute
  DashboardRoute: typeof DashboardRoute
  DataSourcesRoute: typeof DataSourcesRoute
  DisclaimerRoute: typeof DisclaimerRoute
  MapRoute: typeof MapRoute
  MethodologyRoute: typeof MethodologyRoute
  PredictionRoute: typeof PredictionRoute
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  SimulatorRoute: typeof SimulatorRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ValidationRoute: typeof ValidationRoute
  GuidesKosiBasinHydrologyRoute: typeof GuidesKosiBasinHydrologyRoute
  ApiPublicIngestClimateRoute: typeof ApiPublicIngestClimateRoute
  ApiPublicOtpSendRoute: typeof ApiPublicOtpSendRoute
  ApiPublicOtpVerifyRoute: typeof ApiPublicOtpVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validation': {
      id: '/validation'
      path: '/validation'
      fullPath: '/validation'
      preLoaderRoute: typeof ValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prediction': {
      id: '/prediction'
      path: '/prediction'
      fullPath: '/prediction'
      preLoaderRoute: typeof PredictionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-sources': {
      id: '/data-sources'
      path: '/data-sources'
      fullPath: '/data-sources'
      preLoaderRoute: typeof DataSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compound': {
      id: '/compound'
      path: '/compound'
      fullPath: '/compound'
      preLoaderRoute: typeof CompoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attributions': {
      id: '/attributions'
      path: '/attributions'
      fullPath: '/attributions'
      preLoaderRoute: typeof AttributionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/kosi-basin-hydrology': {
      id: '/guides/kosi-basin-hydrology'
      path: '/guides/kosi-basin-hydrology'
      fullPath: '/guides/kosi-basin-hydrology'
      preLoaderRoute: typeof GuidesKosiBasinHydrologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/otp/verify': {
      id: '/api/public/otp/verify'
      path: '/api/public/otp/verify'
      fullPath: '/api/public/otp/verify'
      preLoaderRoute: typeof ApiPublicOtpVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/otp/send': {
      id: '/api/public/otp/send'
      path: '/api/public/otp/send'
      fullPath: '/api/public/otp/send'
      preLoaderRoute: typeof ApiPublicOtpSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest/climate': {
      id: '/api/public/ingest/climate'
      path: '/api/public/ingest/climate'
      fullPath: '/api/public/ingest/climate'
      preLoaderRoute: typeof ApiPublicIngestClimateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AlertsRoute: AlertsRoute,
  AttributionsRoute: AttributionsRoute,
  AuthRoute: AuthRoute,
  CompoundRoute: CompoundRoute,
  DashboardRoute: DashboardRoute,
  DataSourcesRoute: DataSourcesRoute,
  DisclaimerRoute: DisclaimerRoute,
  MapRoute: MapRoute,
  MethodologyRoute: MethodologyRoute,
  PredictionRoute: PredictionRoute,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  SimulatorRoute: SimulatorRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ValidationRoute: ValidationRoute,
  GuidesKosiBasinHydrologyRoute: GuidesKosiBasinHydrologyRoute,
  ApiPublicIngestClimateRoute: ApiPublicIngestClimateRoute,
  ApiPublicOtpSendRoute: ApiPublicOtpSendRoute,
  ApiPublicOtpVerifyRoute: ApiPublicOtpVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
